"""
Django settings for IdeaGrapher project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b^gi-f&d1=r^*z&*oac&^)plz@=jx_cb!5&cm@l@c4^8srohge'
CSRF_SECRET_KEY = bytes(''.join(SECRET_KEY[::-1]), encoding='utf-8')  # quick hack

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Eastern'

USE_I18N = True

USE_L10N = True

USE_TZ = True
